# Generated by Django 5.1.2 on 2024-11-08 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'permissions': [('ver_ofertas', 'ver ofertas '), ('crear_ofertas', 'crear ofertas'), ('editar_ofertas', 'editar ofertas'), ('eliminar_ofertas', 'eliminar ofertas')]},
        ),
    ]
