# Generated by Django 5.1.2 on 2024-11-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_alter_oferta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={},
        ),
    ]
